version: 2.1

orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@4.4.2

jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install

      - run: npm test

      - run: 
          name: Send custom message to slack.
          command: ./tf.sh
      - slack/notify:
          channel: seun_cci_notify
          event: fail
          template: basic_fail_1

      - slack/notify:
          channel: seun_cci_notify
          event: pass
          mentions: '@Seun'
          template: basic_success_1

workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify:
          context: SEUN_CCI_NOTIFY


