version: 2.1

orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@4.4.2

jobs:
  build-test-and-notify:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run: npm test
      - slack/notify:
          channel: circleci-demo
          event: pass
          template: success_tagged_deploy_1

      - slack/notify:
          channel: circleci-demo
          event: fail
          mentions: '@Seun'
          template: basic_fail_1

workflows:
  build-and-notify:
    jobs:
      - build-test-and-notify:
          context: notify-sla
